-- pVW_EmpGradeSTAT

select 
(select Title from oCD_DepType where ID=a.DepType) as 项目,N'浙商证券' as 公司,
a.Title as 类别,b1.GenderM+b2.GenderF as 人数,b1.GenderM as 性别_男,b2.GenderF as 性别_女,b3.AVGAge as 平均年龄,b4.HighLev_ASSTT as 学历_大专及以下,b5.HighLev_UGTT as 学历_本科,b6.HighLev_MSTT as 学历_硕士,b7.HighLev_DTTT as 学历_博士,b8.WorkDate1t5YTT as 从业年限_工龄1到5年,b9.WorkDate5t10YTT as 从业年限_工龄5到10年,b10.WorkDate10YTT as 从业年限_工龄10年以上,b11.JoinDate3YTT as 从业年限_司龄3年以上,
c.JoinMM as 当月入职人数,d.JoinYY as 当年入职人数合计,e.LeaMM as 当月离职人数,f.LeaYY as 当年离职人数合计,a.xOrder
from eCD_EmpGrade a
left join oCD_DepType b on ISNULL(b.isDisabled,0)=0  and a.DepType=b.ID and b.ID=1
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as GenderM from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.Gender=1 group by m.EmpGrade,o.deptype) b1 on a.ID=b1.EmpGrade and b.ID=b1.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as GenderF from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.Gender=2 group by m.EmpGrade,o.deptype) b2 on a.ID=b2.EmpGrade and b.ID=b2.DepType
left join (select m.EmpGrade,o.deptype,AVG(DATEDIFF(YY,n.BirthDay,GETDATE())) as AVGAge from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) group by m.EmpGrade,o.deptype) b3 on a.ID=b3.EmpGrade and b.ID=b3.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as HighLev_ASSTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.HighLevel in (4,5,6,7,8,9,10) group by m.EmpGrade,o.deptype) b4 on a.ID=b4.EmpGrade and b.ID=b4.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as HighLev_UGTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.HighLevel=3 group by m.EmpGrade,o.deptype) b5 on a.ID=b5.EmpGrade and b.ID=b5.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as HighLev_MSTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.HighLevel=2 group by m.EmpGrade,o.deptype) b6 on a.ID=b6.EmpGrade and b.ID=b6.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as HighLev_DTTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and n.HighLevel=1 group by m.EmpGrade,o.deptype) b7 on a.ID=b7.EmpGrade and b.ID=b7.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as WorkDate1t5YTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and DATEDIFF(YY,n.WorkBeginDate,GETDATE())>=1 and DATEDIFF(YY,n.WorkBeginDate,GETDATE())<5 group by m.EmpGrade,o.deptype) b8 on a.ID=b8.EmpGrade and b.ID=b8.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as WorkDate5t10YTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and DATEDIFF(YY,n.WorkBeginDate,GETDATE())>=5 and DATEDIFF(YY,n.WorkBeginDate,GETDATE())<10 group by m.EmpGrade,o.deptype) b9 on a.ID=b9.EmpGrade and b.ID=b9.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as WorkDate10YTT from eEmployee m,eDetails n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and DATEDIFF(YY,n.WorkBeginDate,GETDATE())>=10 group by m.EmpGrade,o.deptype) b10 on a.ID=b10.EmpGrade and b.ID=b10.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.EID) as JoinDate3YTT from eEmployee m,eStatus n,oDepartment o where m.EID=n.EID and m.DepID=o.DepID and m.Status not in (4,5) and DATEDIFF(YY,n.JoinDate,GETDATE())>=3 group by m.EmpGrade,o.deptype) b11 on a.ID=b11.EmpGrade and b.ID=b11.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.conBeginDate) as JoinMM from eStaff_all m,oDepartment o where DATEDIFF(MM,conBeginDate,GETDATE())=0 and m.DepID=o.DepID group by m.EmpGrade,o.deptype) c on a.ID=c.EmpGrade and b.ID=c.DepType
left join (select m.EmpGrade,o.deptype,COUNT(m.conBeginDate) as JoinYY from eStaff_all m,oDepartment o where DATEDIFF(YY,conBeginDate,GETDATE())=0 and m.DepID=o.DepID group by m.EmpGrade,o.deptype) d on a.ID=d.EmpGrade and b.ID=d.DepType
left join (select n.EmpGrade,o.deptype,COUNT(m.leavedate) as LeaMM from eLeave_all m,eEmployee n,oDepartment o where m.badge=n.Badge and m.DepID=o.DepID and DATEDIFF(MM,m.leavedate,GETDATE())=0 group by n.EmpGrade,o.deptype) e on a.ID=e.EmpGrade and b.ID=e.DepType
left join (select n.EmpGrade,o.deptype,COUNT(m.leavedate) as LeaYY from eLeave_all m,eEmployee n,oDepartment o where m.badge=n.Badge and m.DepID=o.DepID and DATEDIFF(YY,m.leavedate,GETDATE())=0 group by n.EmpGrade,o.deptype) f on a.ID=f.EmpGrade and b.ID=f.DepType
where ISNULL(a.isDisabled,0)=0
order by a.xorder,b.xOrder