-- HRL_EMP_INFO_MASTER

select emp_id,emp_code,uid,chn_name,eng_name,other_name,identity_card,date_of_birth,gender,marriage_type_id,nation,state,city,living_address,living_zipcode,
hukou_address,hukou_zipcode,biz_phone,home_phone,mobile_phone,email,emp_basic_remarks,is_salary_pay,quit_date,quit_type_id,quit_reason_id,quit_pension_date,
quit_housing_date,quit_file_date,compensation,employee_date,society_work_date,recruit_source_type_id,hr_level,labor_book,is_probation,probation_end_date,
is_manager,is_sevice_agency_emp,is_foreign_emp,nationality,visa_expiration_date,passport_number,emp_hr_remarks,org_value_id1,org_value_id2,org_value_id3,org_value_id4,
org_value_id5,org_value_id6,org_value_id7,org_value_id8,change_org_reason,change_org_date,max_level_org_value_id,current_position_code,change_position_date,
change_position_reason,current_position_desc,supervisor,created_by,creation_date,last_updated_by,last_update_date,photo,status_code,
Leaving_Housing_Account,emp_type_code,emp_status_code,born_addr,passport_invalid_date,emp_category_code
from OPENQUERY(HRLINK, 'SELECT * FROM DBO.EMP_INFO_MASTER')